--2022-11-17 22:54:28--  http://www.ensembl.org/biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%3C!DOCTYPE%20Query%3E%3CQuery%20%20virtualSchemaName%20=%20%22default%22%20formatter%20=%20%22TSV%22%20header%20=%20%221%22%20uniqueRows%20=%20%220%22%20count%20=%20%22%22%20datasetConfigVersion%20=%20%220.6%22%20%3E%3CDataset%20name%20=%20%22hsapiens_gene_ensembl%22%20interface%20=%20%22default%22%20%3E%3CFilter%20name%20=%20%22transcript_biotype%22%20value%20=%20%22protein_coding%22/%3E%3CFilter%20name%20=%20%22biotype%22%20value%20=%20%22protein_coding%22/%3E%3CFilter%20name%20=%20%22hgnc_symbol%22%20value%20=%20%22ACTC1,ACTN2,CSRP3,MYBPC3,MYH6,MYH7,MYL2,MYL3,MYOZ2,LDB3,TCAP,TNNC1,TNNI3,TNNT2,TPM1,TRIM63,PLN,JPH2,FLNC,ALPK3,LMNA,FHL1,NEXN,VCL,OBSCN,MYOM2,CASQ2,CAV3,MYLK2,CRYAB%22/%3E%3CAttribute%20name%20=%20%22ensembl_gene_id%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_transcript_id%22%20/%3E%3CAttribute%20name%20=%20%22chromosome_name%22%20/%3E%3CAttribute%20name%20=%20%22refseq_peptide%22%20/%3E%3CAttribute%20name%20=%20%22ensembl_peptide_id%22%20/%3E%3CAttribute%20name%20=%20%22description%22%20/%3E%3CAttribute%20name%20=%20%22strand%22%20/%3E%3CAttribute%20name%20=%20%22start_position%22%20/%3E%3CAttribute%20name%20=%20%22end_position%22%20/%3E%3CAttribute%20name%20=%20%22external_gene_name%22%20/%3E%3CAttribute%20name%20=%20%22gene_biotype%22%20/%3E%3CAttribute%20name%20=%20%22transcript_biotype%22%20/%3E%3CAttribute%20name%20=%20%22uniprot_isoform%22%20/%3E%3CAttribute%20name%20=%20%22transcript_length%22%20/%3E%3C/Dataset%3E%3C/Query%3E
Resolving www.ensembl.org (www.ensembl.org)... 193.62.193.83
Connecting to www.ensembl.org (www.ensembl.org)|193.62.193.83|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘biomart_table.tsv’

     0K .......... .......... .......... ....                  2.41K=14s

2022-11-17 22:54:49 (2.41 KB/s) - ‘biomart_table.tsv’ saved [35281]

Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_005150' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/ACTC1.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ACTC1.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/ACTC1.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 15:
Failed to read the regions: 15:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ACTC1.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ACTC1.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ACTC1.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ACTC1.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/ACTC1.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ACTC1.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/ACTC1.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTC1.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001094' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/ACTN2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ACTN2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/ACTN2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ACTN2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ACTN2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ACTN2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ACTN2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/ACTN2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ACTN2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/ACTN2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ACTN2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_065829' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/ALPK3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ALPK3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/ALPK3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 15:
Failed to read the regions: 15:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ALPK3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ALPK3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/ALPK3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/ALPK3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/ALPK3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/ALPK3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/ALPK3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/ALPK3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001223' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/CASQ2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CASQ2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/CASQ2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CASQ2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CASQ2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CASQ2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CASQ2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/CASQ2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CASQ2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/CASQ2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CASQ2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001225' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/CAV3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CAV3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/CAV3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 3:
Failed to read the regions: 3:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CAV3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CAV3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CAV3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CAV3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/CAV3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CAV3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/CAV3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CAV3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001876' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/CRYAB.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CRYAB.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/CRYAB.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 11:
Failed to read the regions: 11:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CRYAB.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CRYAB.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CRYAB.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CRYAB.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/CRYAB.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CRYAB.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/CRYAB.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CRYAB.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_003467' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/CSRP3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CSRP3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/CSRP3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 11:
Failed to read the regions: 11:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CSRP3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CSRP3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/CSRP3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/CSRP3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/CSRP3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/CSRP3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/CSRP3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/CSRP3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001440' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/FHL1.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/FHL1.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/FHL1.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): X:
Failed to read the regions: X:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/FHL1.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/FHL1.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/FHL1.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/FHL1.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/FHL1.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/FHL1.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/FHL1.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FHL1.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_001449' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/FLNC.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/FLNC.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/FLNC.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 7:
Failed to read the regions: 7:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/FLNC.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/FLNC.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/FLNC.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/FLNC.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/FLNC.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/FLNC.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/FLNC.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/FLNC.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_065166' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/JPH2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/JPH2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/JPH2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 20:
Failed to read the regions: 20:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/JPH2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/JPH2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/JPH2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/JPH2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/JPH2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/JPH2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/JPH2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/JPH2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_009009' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/LDB3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/LDB3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/LDB3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 10:
Failed to read the regions: 10:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/LDB3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/LDB3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/LDB3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/LDB3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/LDB3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/LDB3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/LDB3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LDB3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_005563' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/LMNA.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/LMNA.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/LMNA.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/LMNA.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/LMNA.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/LMNA.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/LMNA.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/LMNA.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/LMNA.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/LMNA.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/LMNA.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000247' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYBPC3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYBPC3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYBPC3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 11:
Failed to read the regions: 11:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYBPC3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYBPC3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYBPC3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYBPC3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYBPC3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYBPC3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYBPC3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYBPC3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_002462' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYH6.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYH6.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYH6.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 14:
Failed to read the regions: 14:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYH6.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYH6.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYH6.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYH6.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYH6.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYH6.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYH6.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH6.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000248' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYH7.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYH7.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYH7.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 14:
Failed to read the regions: 14:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYH7.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYH7.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYH7.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYH7.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYH7.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYH7.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYH7.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYH7.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000423' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYL2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYL2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYL2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 12:
Failed to read the regions: 12:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYL2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYL2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYL2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYL2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYL2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYL2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYL2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000249' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYL3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYL3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYL3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 3:
Failed to read the regions: 3:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYL3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYL3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYL3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYL3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYL3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYL3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYL3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYL3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_149109' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYLK2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYLK2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYLK2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 20:
Failed to read the regions: 20:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYLK2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYLK2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYLK2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYLK2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYLK2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYLK2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYLK2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYLK2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_003961' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYOM2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYOM2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYOM2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 8:
Failed to read the regions: 8:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYOM2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYOM2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYOM2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYOM2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYOM2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYOM2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYOM2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOM2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_057683' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/MYOZ2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYOZ2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/MYOZ2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 4:
Failed to read the regions: 4:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYOZ2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYOZ2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/MYOZ2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/MYOZ2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/MYOZ2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/MYOZ2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/MYOZ2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/MYOZ2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_653174' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/NEXN.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/NEXN.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/NEXN.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/NEXN.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/NEXN.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/NEXN.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/NEXN.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/NEXN.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/NEXN.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/NEXN.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/NEXN.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_443075' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/OBSCN.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/OBSCN.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/OBSCN.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/OBSCN.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/OBSCN.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/OBSCN.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/OBSCN.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/OBSCN.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/OBSCN.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/OBSCN.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/OBSCN.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_002658' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/PLN.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/PLN.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/PLN.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 6:
Failed to read the regions: 6:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/PLN.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/PLN.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/PLN.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/PLN.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/PLN.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/PLN.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/PLN.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/PLN.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_003664' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TCAP.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TCAP.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TCAP.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 17:
Failed to read the regions: 17:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TCAP.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TCAP.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TCAP.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TCAP.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TCAP.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TCAP.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TCAP.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TCAP.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_003271' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TNNC1.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNC1.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TNNC1.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 3:
Failed to read the regions: 3:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNC1.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNC1.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNC1.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNC1.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TNNC1.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNC1.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TNNC1.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNC1.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000354' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TNNI3.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNI3.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TNNI3.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 19:
Failed to read the regions: 19:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNI3.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNI3.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNI3.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNI3.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TNNI3.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNI3.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TNNI3.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNI3.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000355' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TNNT2.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNT2.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TNNT2.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNT2.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNT2.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TNNT2.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TNNT2.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TNNT2.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TNNT2.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TNNT2.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TNNT2.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_000357' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TPM1.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TPM1.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TPM1.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 15:
Failed to read the regions: 15:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TPM1.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TPM1.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TPM1.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TPM1.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TPM1.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TPM1.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TPM1.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TPM1.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_115977' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/TRIM63.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TRIM63.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/TRIM63.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 1:
Failed to read the regions: 1:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TRIM63.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TRIM63.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/TRIM63.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/TRIM63.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/TRIM63.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/TRIM63.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/TRIM63.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/TRIM63.annot.poplevel.vcf.gz: No such file or directory
Traceback (most recent call last):
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <module>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
    return self.apply_standard()
  File "/n/app/anaconda/v3/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/n/groups/marks/databases/ukbiobank/users/ralphest/mit6.8610-project/get_data/clean_annot.py", line 24, in <lambda>
    df['protein_idx'] = df['EVEmap_REFSEQ_PROTEIN'].str.split(',').apply(lambda x: x.index(refseq_id))
ValueError: 'NP_003364' is not in list
[bgzip] No such file or directory: ../data/temp/annot_table/VCL.annot.tab
[E::hts_open_format] Failed to open file "../data/temp/annot_table/VCL.annot.tab.gz" : No such file or directory
Couldn't open "../data/temp/annot_table/VCL.annot.tab.gz": No such file or directory
[E::_regions_init_string] Could not parse the region(s): 10:
Failed to read the regions: 10:
Error: File read failure.
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/VCL.id.filtered.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/VCL.id.filtered.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/unannot_vcf/VCL.unannot.vcf.gz" : No such file or directory
Failed to read from ../data/temp/unannot_vcf/VCL.unannot.vcf.gz: No such file or directory
rm: cannot remove ‘../data/temp/unannot_vcf/VCL.id.filtered.vcf.gz’: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_table/VCL.annot.tab.gz" : No such file or directory
Failed to open ../data/temp/annot_table/VCL.annot.tab.gz
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz: No such file or directory
[E::hts_open_format] Failed to open file "../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz" : No such file or directory
Failed to read from ../data/temp/annot_vcf/VCL.annot.poplevel.vcf.gz: No such file or directory
